#!/bin/bash
#in use update MAC


dmesg |grep " ..:..:..:..:.."
if [ $? -ne 0 ];then
DMESG='cat /var/log/dmesg.old'
else
DMESG='dmesg'
fi

#for net device
NET_COUNT=0

lsmod | grep bond
if [ $? -ne 0 ];then
MAC=$(cat /sys/devices/*/*/*/net/*/address|sed 's@ @\n@g'|grep "..:..:..:..:.." |sort -u)
else
MAC=$(cat /proc/net/bonding/* /sys/devices/*/*/*/net/*/address|sed 's@ @\n@g'|grep "..:..:..:..:.."|sort -u)
fi

BIOS=$(${DMESG} |grep -E 'igb|ixgbe|bnx2|tg3|e1000|pcnet32'  |sed 's@ @\n@g'|grep "..:..:..:..:.."|sort -u)
NOBIOS=$(echo "${MAC}"|grep -E -v "${BIOS}")
IXGBE=$(${DMESG} |grep -i 'ixgbe'|sort -u|sed 's@ @\n@g'|grep "..:..:..:..:..")
BNX2X=$(${DMESG} |grep -i 'bnx2x'|sort -u|sed 's@ @\n@g'|grep "..:..:..:..:..")
BNX2=$(${DMESG} |grep -i 'bnx2 '|sort -u|sed 's@ @\n@g'|grep "..:..:..:..:..")
IGB=$(${DMESG} |grep -i 'igb'|sort -u|sed 's@ @\n@g'|grep "..:..:..:..:..")
TG3=$(${DMESG} |grep -i 'tg3'|sort -u|sed 's@ @\n@g'|grep "..:..:..:..:..")
E1000=$(${DMESG} |grep -i 'e1000'|sort -u|sed 's@ @\n@g'|grep "..:..:..:..:.."=)
PCNET32=$(${DMESG} |grep -i 'pcnet32'|sort -u|sed 's@ @\n@g'|grep "..:..:..:..:..")

function NET_DEV()
{
DEV=$1
DEV_NU=$(echo "${DEV}"|awk '{if($0!=""){x=x+1}}END{print int(x)}')
for ((i=0;i<${DEV_NU};i++))
do
HWADDR=$(echo "${DEV}"|sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'|awk "NR==$[${i}+1]{print}")

sed -i '/HWADDR/d' /etc/sysconfig/network-scripts/ifcfg-eth${NET_COUNT}
sed -i '/UUID/d' /etc/sysconfig/network-scripts/ifcfg-eth${NET_COUNT}
echo "HWADDR=${HWADDR}" | tee -a /etc/sysconfig/network-scripts/ifcfg-eth${NET_COUNT}
NET_COUNT=$((NET_COUNT+1))
done
}

cat > /etc/udev/rules.d/70-persistent-net.rules << __EOF__
# This file was automatically generated by the /lib/udev/write_net_rules
# program, run by the persistent-net-generator.rules rules file.
#
# You can modify it, as long as you keep each rule on a single
# line, and change only the value of the NAME= key.

__EOF__


sed -i 's/"//g' /etc/sysconfig/network-scripts/ifcfg-eth*
sed -i "s/DEVICE=.*/DEVICE=eth0/g" /etc/sysconfig/network-scripts/ifcfg-eth1
sed -i "s/DEVICE=.*/DEVICE=eth1/g" /etc/sysconfig/network-scripts/ifcfg-eth0

for DEV in "${NOBIOS}" "${IXGBE}" "${BNX2X}" "${BNX2}" "${IGB}" "${TG3}" "${E1000}" "${PCNET32}"
do 
NET_DEV "${DEV}"
done

/sbin/modprobe ipmi_msghandler > /dev/null 2>&1 &
/sbin/modprobe ipmi_devintf  > /dev/null 2>&1 &
/sbin/modprobe ipmi_si > /dev/null 2>&1 &
echo 100 |tee /sys/module/ipmi_si/parameters/kipmid_max_busy_us &
/sbin/modprobe ipmi_poweroff > /dev/null 2>&1 &
/sbin/modprobe ipmi_watchdog > /dev/null 2>&1 &
service ipmi start &
sleep 3
ipmitool chassis power reset 

